### PR TITLE
Omit writing certificate and key to disk

### LINKED ISSUE #76: Racy pemfile creation causes errors for parallel builds
I'm consistently getting errors when trying to build two images in parallel with the same subscription. It looks like the first build enters [this if block](https://github.com/MSOpenTech/packer-azure/blob/3cb56d474c7481ba4f7ca265f7afea734c37242c/packer/builder/azure/driver_restapi/request/SubscriptionManagement.go#L168-223) and writes the tag file, then the next build sees the tagfile and immediately tries to read the pemfile, even though it hasn't finished being written yet.

This results in an error like this:
```
Build 'XXXX' errored: Error creating request manager: Failed to Parse PublishSettings: open /home/ubuntu/.packer_azure/XXXX/cert.pem: no such file or directory
```

### PR DESCRIPTION
**Pull request by paulmey**
Fixes #76

### CODE REVIEW

File: packer/builder/azure/driver_restapi/constants/stateBag.go [hunk 1]
```diff
@@ -17,17 +16,17 @@ const (
...
-	HardDiskName       string = "hardDiskName"
-	MediaLink          string = "mediaLink"
-	SSHHost            string = "sshHost"
+	Config         string = "config"
+	Ui             string = "ui"
+	RequestManager string = "requestManager"
+	PrivateKey     string = "privateKey"
+	Certificate    string = "certificate"
+	Thumbprint     string = "thumbprint"
+	OsImageName    string = "osImageName"
```
Comment (ahmetalpbalkan) [inline packer/builder/azure/driver_restapi/constants/stateBag.go]: OS
